route:
  receiver: "default"

receivers:
  - name: "default"
    email_configs:
      - to: "seu-email@gmail.com"
        from: "alerta@api.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "seu-email@gmail.com"
        auth_password: "SENHA_APP_GMAIL"